In [3]:
from sklearn import datasets
from sklearn import model_selection as ms
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
iris= datasets.load_iris()

In [5]:
x_train, x_test, y_train, y_test= ms.train_test_split(iris.data, iris.target, test_size= 0.2)

In [6]:
algo1= LinearRegression()
ms.cross_val_score(algo1, x_train, y_train)

array([0.95063427, 0.84306933, 0.89472871, 0.94444747, 0.97761243])

## Zero Cross Val Score

In [7]:
algo2= LinearRegression()
ms.cross_val_score(algo2, iris.data, iris.target)

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

## Get rid of Zero Cross Val Score

In [13]:
algo3= LinearRegression()
ms.cross_val_score(algo3, iris.data, iris.target, cv= ms.KFold(n_splits= 3, shuffle= True))

array([0.94630284, 0.91038635, 0.90685974])